"""Add metrics to SystemHealth

Revision ID: 25e32419477a
Revises: 5ffeaeac33ee
Create Date: 2026-07-19 21:44:32.955296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25e32419477a'
down_revision: Union[str, None] = '5ffeaeac33ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('system_health', sa.Column('metrics', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('system_health', 'metrics')
    # ### end Alembic commands ###
