"""add locations

Revision ID: 483a2d7a1ba7
Revises: b4353bf7a7ca
Create Date: 2026-07-18 20:28:53.983407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '483a2d7a1ba7'
down_revision: Union[str, None] = 'b4353bf7a7ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interest_profiles', sa.Column('preferred_locations', sa.JSON(), nullable=True))
    op.add_column('summaries', sa.Column('locations', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('summaries', 'locations')
    op.drop_column('interest_profiles', 'preferred_locations')
    # ### end Alembic commands ###
