"""Add saved_articles table

Revision ID: 4fbc794744de
Revises: 5555ae48ad77
Create Date: 2026-07-23 01:01:02.779382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fbc794744de'
down_revision: Union[str, None] = '5555ae48ad77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saved_articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('processed_article_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['processed_article_id'], ['processed_articles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saved_articles_id'), 'saved_articles', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_saved_articles_id'), table_name='saved_articles')
    op.drop_table('saved_articles')
    # ### end Alembic commands ###
