"""Add SystemHealth

Revision ID: 5ffeaeac33ee
Revises: 483a2d7a1ba7
Create Date: 2026-07-19 19:42:38.288620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ffeaeac33ee'
down_revision: Union[str, None] = '483a2d7a1ba7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_health',
    sa.Column('component_name', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('last_run', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('component_name')
    )
    op.create_index(op.f('ix_system_health_component_name'), 'system_health', ['component_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_system_health_component_name'), table_name='system_health')
    op.drop_table('system_health')
    # ### end Alembic commands ###
