"""Add User and InterestProfile models

Revision ID: b4353bf7a7ca
Revises: ffbcaf3be759
Create Date: 2026-07-18 19:35:55.340710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4353bf7a7ca'
down_revision: Union[str, None] = 'ffbcaf3be759'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('interest_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('focus_tags', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_interest_profiles_id'), 'interest_profiles', ['id'], unique=False)
    op.create_table('business_entities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('competitors', sa.JSON(), nullable=True),
    sa.Column('target_sectors', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['interest_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_entities_id'), 'business_entities', ['id'], unique=False)
    op.create_table('user_article_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('processed_article_id', sa.Integer(), nullable=True),
    sa.Column('personal_relevance_score', sa.Integer(), nullable=True),
    sa.Column('relevance_category', sa.String(), nullable=True),
    sa.Column('relevance_reason', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['processed_article_id'], ['processed_articles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_article_scores_id'), 'user_article_scores', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_article_scores_id'), table_name='user_article_scores')
    op.drop_table('user_article_scores')
    op.drop_index(op.f('ix_business_entities_id'), table_name='business_entities')
    op.drop_table('business_entities')
    op.drop_index(op.f('ix_interest_profiles_id'), table_name='interest_profiles')
    op.drop_table('interest_profiles')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
