"""Initial schema

Revision ID: d6d900de977f
Revises: 
Create Date: 2026-07-16 14:40:20.594132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = 'd6d900de977f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('priority', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_id'), 'events', ['id'], unique=False)
    op.create_table('rss_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('frequency_minutes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rss_sources_id'), 'rss_sources', ['id'], unique=False)
    op.create_index(op.f('ix_rss_sources_name'), 'rss_sources', ['name'], unique=False)
    op.create_index(op.f('ix_rss_sources_url'), 'rss_sources', ['url'], unique=True)
    op.create_table('raw_articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('content_hash', sa.String(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['rss_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_articles_content_hash'), 'raw_articles', ['content_hash'], unique=True)
    op.create_index(op.f('ix_raw_articles_id'), 'raw_articles', ['id'], unique=False)
    op.create_index(op.f('ix_raw_articles_url'), 'raw_articles', ['url'], unique=True)
    op.create_table('processed_articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raw_article_id', sa.Integer(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('published_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['raw_article_id'], ['raw_articles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('raw_article_id')
    )
    op.create_index(op.f('ix_processed_articles_id'), 'processed_articles', ['id'], unique=False)
    op.create_table('embeddings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('processed_article_id', sa.Integer(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.Vector(dim=768), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['processed_article_id'], ['processed_articles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('processed_article_id')
    )
    op.create_index(op.f('ix_embeddings_id'), 'embeddings', ['id'], unique=False)
    op.create_table('summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('processed_article_id', sa.Integer(), nullable=True),
    sa.Column('bullet_points', sa.Text(), nullable=True),
    sa.Column('technical_impact', sa.Text(), nullable=True),
    sa.Column('business_impact', sa.Text(), nullable=True),
    sa.Column('business_relevant', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['processed_article_id'], ['processed_articles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('processed_article_id')
    )
    op.create_index(op.f('ix_summaries_id'), 'summaries', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_summaries_id'), table_name='summaries')
    op.drop_table('summaries')
    op.drop_index(op.f('ix_embeddings_id'), table_name='embeddings')
    op.drop_table('embeddings')
    op.drop_index(op.f('ix_processed_articles_id'), table_name='processed_articles')
    op.drop_table('processed_articles')
    op.drop_index(op.f('ix_raw_articles_url'), table_name='raw_articles')
    op.drop_index(op.f('ix_raw_articles_id'), table_name='raw_articles')
    op.drop_index(op.f('ix_raw_articles_content_hash'), table_name='raw_articles')
    op.drop_table('raw_articles')
    op.drop_index(op.f('ix_rss_sources_url'), table_name='rss_sources')
    op.drop_index(op.f('ix_rss_sources_name'), table_name='rss_sources')
    op.drop_index(op.f('ix_rss_sources_id'), table_name='rss_sources')
    op.drop_table('rss_sources')
    op.drop_index(op.f('ix_events_id'), table_name='events')
    op.drop_table('events')
    # ### end Alembic commands ###
