"""Add missing AI extraction fields

Revision ID: ffbcaf3be759
Revises: 8b4f85f79619
Create Date: 2026-07-18 18:44:39.554672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffbcaf3be759'
down_revision: Union[str, None] = '8b4f85f79619'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('summaries', sa.Column('entities', sa.JSON(), nullable=True))
    op.add_column('summaries', sa.Column('sentiment', sa.String(), nullable=True))
    op.add_column('summaries', sa.Column('action_hint', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('summaries', 'action_hint')
    op.drop_column('summaries', 'sentiment')
    op.drop_column('summaries', 'entities')
    # ### end Alembic commands ###
